import type { Metadata } from "next";
import { Geist_Mono, Rajdhani, Montserrat } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import NavWrapper from "./NavWrapper";

const rajdhani = Rajdhani({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ascension - Your journey to learn ML",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="theme-preference" strategy="beforeInteractive">
          {`(() => {
            const savedTheme = localStorage.getItem("theme");
            const theme = savedTheme ?? (window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
            document.documentElement.classList.toggle("dark", theme === "dark");
            document.documentElement.style.colorScheme = theme;
          })();`}
        </Script>
      </head>
      <body
        className={`${rajdhani.variable} ${montserrat.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <NavWrapper>{children}</NavWrapper>
      </body>
    </html>
  );
}
