import type { Metadata } from "next";
import { Geist_Mono, Rajdhani, Montserrat } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeContext";
import "./globals.css";
import NavWrapper from "./NavWrapper";
import GlobalAudio from "@/components/GlobalAudio";
import { Toaster } from "sonner";

const rajdhani = Rajdhani({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ascensioz - Your journey to learn ML",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${rajdhani.variable} ${montserrat.variable} ${geistMono.variable} antialiased bg-background text-foreground selection:bg-[var(--color-primary)]/20 selection:text-[var(--color-text)]`}
      >
        <ThemeProvider>
          <NavWrapper>{children}</NavWrapper>
          <GlobalAudio />
          <Toaster position="bottom-right" richColors />
        </ThemeProvider>
      </body>
    </html>
  );
}
